import {calculate,money} from './calculator.js';
import {CATALOG_VERSION,mergePrinterCatalog} from './printerCatalog.js';
const KEY='3d-price-v1';
const defaultPrinters=[{id:'p1',name:'Impressora doméstica (exemplo)',price:2500,life:4000,watts:120,maintenance:.35}];
const defaultMaterials=[{id:'m1',name:'PLA (exemplo)',price:90,grams:1000},{id:'m2',name:'PETG (exemplo)',price:110,grams:1000},{id:'m3',name:'ABS (exemplo)',price:100,grams:1000},{id:'m4',name:'TPU (exemplo)',price:150,grams:1000}];
const defaults={name:'',printer:'p1',material:'m1',grams:45,quantity:1,hours:3,minutes:0,spoolPrice:90,spoolGrams:1000,watts:120,kwh:.95,machinePrice:2500,lifeHours:4000,maintenance:.35,consumables:1,packaging:2,failure:8,laborHours:.35,laborRate:25,other:0,margin:25,marketplace:0,payment:4,taxes:0,discount:0,shipping:0};
const el=id=>document.getElementById(id);
let store;
try{store=JSON.parse(localStorage.getItem(KEY)||'null')}catch{store=null}
if(!store||typeof store!=='object')store={};
store={printerCatalogVersion:Number(store.printerCatalogVersion)||0,printers:Array.isArray(store.printers)?store.printers:defaultPrinters,materials:Array.isArray(store.materials)?store.materials:defaultMaterials,history:Array.isArray(store.history)?store.history:[],draft:{...defaults,...(store.draft||{})},dark:!!store.dark};
store.printers=mergePrinterCatalog(store.printers,store.printerCatalogVersion);
store.printerCatalogVersion=CATALOG_VERSION;
const fields=Object.keys(defaults), persisted=()=>{try{localStorage.setItem(KEY,JSON.stringify(store))}catch{alert('Armazenamento indisponível. Exporte um backup ou libere espaço no navegador.')}};
const text=(s)=>String(s??'');const safe=s=>text(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=()=>crypto.randomUUID?.()||String(Date.now())+Math.random().toString(36).slice(2);
function renderSelectors(){for(const [id,list] of [['printer',store.printers],['material',store.materials]]){el(id).innerHTML=list.map(v=>`<option value="${safe(v.id)}">${safe(v.name)}</option>`).join('');if(list.some(v=>v.id===store.draft[id]))el(id).value=store.draft[id];else {store.draft[id]=list[0]?.id||'';el(id).value=store.draft[id]}}}
function preset(type){const p=store[type==='printer'?'printers':'materials'].find(v=>v.id===store.draft[type]);if(!p)return; if(type==='printer'){Object.assign(store.draft,{machinePrice:p.price,lifeHours:p.life,watts:p.watts,maintenance:p.maintenance});if(el('printerExampleNotice'))el('printerExampleNotice').hidden=!p.example;}else Object.assign(store.draft,{spoolPrice:p.price,spoolGrams:p.grams});paintFields()}
function paintFields(){for(const k of fields){if(el(k))el(k).value=store.draft[k]??''}}
function read(){for(const k of fields){const input=el(k);store.draft[k]=input.type==='number'?input.value===''?NaN:Number(input.value):input.value}persisted();update()}
let current=null;
function update(){try{current=calculate(store.draft);el('error').textContent='';const r=current;el('suggested').textContent=money(r.suggested);el('perUnit').textContent=money(r.perUnit)+' por peça • '+r.quantity+' peça(s)';el('cost').textContent=money(r.cost);el('minimum').textContent=money(r.minimum);el('profit').textContent=money(r.profit);el('actualMargin').textContent=r.actualMargin.toFixed(1).replace('.',',')+'%';el('totalRepeat').textContent=money(r.cost);el('breakdown').innerHTML=r.items.map(i=>`<div class="cost-row"><span>${safe(i.label)}</span><strong>${money(i.value)}</strong></div><div class="bar"><div style="width:${r.cost>0?Math.max(0,Math.min(100,i.value/r.cost*100)):0}%"></div></div>`).join('');el('save').disabled=el('print').disabled=false}catch(e){current=null;el('error').textContent=e.message;['suggested','perUnit','cost','minimum','profit','actualMargin','totalRepeat'].forEach(k=>el(k).textContent='—');el('breakdown').innerHTML='';el('save').disabled=el('print').disabled=true}}
function nav(view){document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id===view));document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===view));if(view==='profiles')renderProfiles();if(view==='history')renderHistory();window.scrollTo(0,0)}
function renderProfiles(){for(const [type,listId] of [['printers','printerList'],['materials','materialList']]){el(listId).innerHTML=store[type].map(v=>`<div class="profile-row"><div><strong>${safe(v.name)}</strong><small>${type==='printers'?money(v.price)+' • '+v.life+'h • '+v.watts+'W':money(v.price)+' / '+v.grams+'g'}</small></div><button class="delete" data-delete="${safe(v.id)}" data-type="${type}">Remover</button></div>`).join('')||'<p>Nenhum perfil cadastrado.</p>'}}
function renderHistory(){el('historyList').innerHTML=store.history.map(h=>`<div class="history-row"><div><strong>${safe(h.draft.name||'Peça sem nome')}</strong><small>${new Date(h.created).toLocaleString('pt-BR')} • ${h.draft.quantity} unidade(s)</small></div><div><strong>${money(h.result.suggested)}</strong><div class="row-actions"><button class="secondary" data-load="${safe(h.id)}">Abrir</button><button class="delete" data-remove-history="${safe(h.id)}">Excluir</button></div></div></div>`).join('')||'<p>Nenhum cálculo salvo ainda.</p>'}
function report(){if(!current)return;const r=current,d=store.draft,win=window.open('','_blank');if(!win){alert('Permita pop-ups para gerar o PDF.');return}const rows=r.items.map(i=>`<tr><td>${safe(i.label)}</td><td>${money(i.value)}</td></tr>`).join('');win.document.write(`<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><title>Orçamento 3D Price</title><style>body{font:14px Arial;color:#16233b;padding:25px;max-width:780px;margin:auto}h1{margin:0}small{color:#65748a}table{border-collapse:collapse;width:100%;margin:20px 0}td{padding:10px;border-bottom:1px solid #ddd}td:last-child{text-align:right}h2{margin-top:30px}.total{background:#123443;color:white;padding:20px;font-size:24px;font-weight:bold;border-radius:8px}@page{size:A4;margin:18mm}@media print{body{padding:0}}</style></head><body><h1>3D Price • Estimativa de preço</h1><small>Gerado em ${new Date().toLocaleString('pt-BR')}</small><h2>${safe(d.name||'Peça impressa em 3D')}</h2><p>Quantidade: ${r.quantity} • Material: ${safe(store.materials.find(m=>m.id===d.material)?.name||'—')} • Impressora: ${safe(store.printers.find(m=>m.id===d.printer)?.name||'—')}</p><p>Peso por peça: ${d.grams}g • Tempo do lote: ${r.hours.toFixed(2)}h</p><h2>Custos estimados do lote</h2><table>${rows}<tr><td><strong>Custo total</strong></td><td><strong>${money(r.cost)}</strong></td></tr></table><p>Preço mínimo de equilíbrio: ${money(r.minimum)}</p><div class="total">Preço sugerido do lote: ${money(r.suggested)}</div><p>Preço sugerido por peça: ${money(r.perUnit)}</p><p>Margem prevista: ${r.actualMargin.toFixed(1)}% • Lucro estimado do lote: ${money(r.profit)}</p><small>Estimativa sujeita a custos reais, falhas, impostos e condições de venda. Gerado pelo 3D Price.</small><script>window.onload=()=>window.print()<\/script></body></html>`);win.document.close()}
document.querySelectorAll('.nav-item').forEach(b=>b.addEventListener('click',()=>nav(b.dataset.view)));
fields.forEach(k=>el(k).addEventListener('input',read));
el('printer').addEventListener('change',()=>{store.draft.printer=el('printer').value;preset('printer');persisted();update()});
el('material').addEventListener('change',()=>{store.draft.material=el('material').value;preset('material');persisted();update()});
el('reset').onclick=()=>{if(confirm('Iniciar novo cálculo? Os valores atuais serão substituídos.')){store.draft={...defaults,printer:store.printers[0]?.id||'',material:store.materials[0]?.id||''};renderSelectors();preset('printer');preset('material');persisted();update()}};
el('save').onclick=()=>{if(!current)return;store.history.unshift({id:uid(),created:new Date().toISOString(),draft:{...store.draft},result:current});store.history=store.history.slice(0,300);persisted();alert('Cálculo salvo no histórico deste navegador.')};el('print').onclick=report;
for(const type of ['printer','material'])el(type+'Form').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget);const g=k=>Number(f.get(k));const name=text(f.get('name')).trim();if(!name)return;const item=type==='printer'?{id:uid(),name,price:g('price'),life:g('life'),watts:g('watts'),maintenance:g('maintenance')}:{id:uid(),name,price:g('price'),grams:g('grams')};const values=Object.entries(item).filter(([k])=>!['id','name'].includes(k)).map(([,v])=>v);if(values.some(v=>!Number.isFinite(v)||v<0)|| (type==='printer'&&item.life===0)||(type==='material'&&item.grams===0)){alert('Verifique os valores informados.');return}store[type==='printer'?'printers':'materials'].push(item);store.draft[type]=item.id;preset(type);e.currentTarget.reset();renderSelectors();renderProfiles();persisted();update()});
document.body.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.delete){const key=b.dataset.type;if(store[key].length<=1){alert('Mantenha pelo menos um perfil.');return}if(!confirm('Remover este perfil?'))return;store[key]=store[key].filter(x=>x.id!==b.dataset.delete);renderSelectors();preset(key==='printers'?'printer':'material');renderProfiles();persisted();update()}if(b.dataset.load){const h=store.history.find(x=>x.id===b.dataset.load);if(h){store.draft={...defaults,...h.draft};renderSelectors();paintFields();update();persisted();nav('calculator')}}if(b.dataset.removeHistory){if(!confirm('Excluir cálculo do histórico?'))return;store.history=store.history.filter(x=>x.id!==b.dataset.removeHistory);persisted();renderHistory()}});
el('exportJson').onclick=()=>{const blob=new Blob([JSON.stringify({version:1,...store},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='3d-price-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),2000)};
el('importJson').onclick=()=>el('jsonFile').click();
el('jsonFile').onchange=async e=>{const file=e.target.files?.[0];if(!file)return;try{if(file.size>5e6)throw Error('Arquivo muito grande');const obj=JSON.parse(await file.text());if(obj.version!==1||!Array.isArray(obj.printers)||!Array.isArray(obj.materials)||!Array.isArray(obj.history)||!obj.printers.length||!obj.materials.length)throw Error('Formato inválido');if(!confirm('Substituir os perfis e histórico atuais pelo backup?'))return;store={printers:obj.printers,materials:obj.materials,history:obj.history,draft:{...defaults,...obj.draft},dark:!!obj.dark};persisted();store.printers=mergePrinterCatalog(store.printers,store.printerCatalogVersion);
store.printerCatalogVersion=CATALOG_VERSION;renderSelectors();paintFields();update();renderHistory();applyTheme()}catch(err){alert('Não foi possível importar: '+err.message)}finally{e.target.value=''}};
const applyTheme=()=>{document.body.classList.toggle('dark',store.dark);el('themeBtn').textContent=store.dark?'☼ Claro':'◐ Tema'};el('themeBtn').onclick=()=>{store.dark=!store.dark;applyTheme();persisted()};
renderSelectors();paintFields();if(el('printerExampleNotice'))el('printerExampleNotice').hidden=!store.printers.find(p=>p.id===store.draft.printer)?.example;applyTheme();update();